cfmello/tourails

_.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/pages/home.html.erb
=> fixed buttons in views

app/models/booking.rb, db/migrate/20201203151345_create_bookings.rb, db/schema.rb, test/models/booking_test.rb
Booking model with validations:
- Have a user
- Have a offer
- Have a start date
- Have a end date
- Client and guide must be diferent
- Start date must be in the future
- End date must be grater or equal to start date
=> Booking model created and validated

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, db/schema.rb
Just edition of some pages of css and views to test
=> edition of some pages of css to test

app/assets/stylesheets/pages/_home.scss, app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb
=> Edit views

app/views/devise/shared/_links.html.erb, app/views/shared/_navbar.html.erb, db/schema.rb
=> edition of the view to create new user

app/controllers/bookings_controller.rb, app/views/bookings/_form.html.erb, app/views/bookings/edit.html.erb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb
O usuário pode alterar um agendamento.
A jornada inicia na página do agendamento.
O usuário acessa o formulário e faz as alterações desejadas.
O usuário retorna para a página do agendamento para ver as informações atualizadas.
=> A user can edit a service

app/controllers/bookings_controller.rb, app/views/bookings/show.html.erb, config/routes.rb, db/migrate/20201203200403_add_column_to_booking.rb, db/schema.rb
O usuário pode desistir do serviço.
A jornada começa na página do agendamento.
O usuário clica em desistir, confirma a opção e é redirecionado para a página de ofertas.
=> User give up service

app/views/offers/new.html.erb, app/views/pages/home.html.erb
Just shortcuts, nothing special
=> Improvement in the home page

app/views/bookings/_form.html.erb, app/views/bookings/edit.html.erb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/offers/index.html.erb, app/views/offers/new.html.erb, app/views/offers/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
Change the language to portuguese and some visual style
=> Improvement in visual and style and "lewagoning" the language

app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/index.html.erb, config/routes.rb
O usuário pode listar seus agendamentos como turista
Inclui correções no modelo Booking
=> A user can see his/her list of bookings

config/application.rb, config/locales/devise.pt-BR.yml, config/locales/pt-BR.yml
Tradução das mensagens do devise e algumas coisas do rails
=> tradução do devise + rails

app/controllers/offers_controller.rb, app/views/offers/edit.html.erb, app/views/offers/show.html.erb
O anunciante pode alterar a descrição da oferta e desativar
=> Anunciante pode alterar dados da oferta

app/assets/stylesheets/components/_alert.scss, app/controllers/bookings_controller.rb, app/controllers/offers_controller.rb
Melhoria na experiência do usuário com mensagens de erro e confirmação tipo flash
=> Using flashes to show messages

app/views/bookings/edit.html.erb, app/views/bookings/index.html.erb, app/views/bookings/show.html.erb, app/views/offers/index.html.erb, app/views/pages/home.html.erb
=> Styles buttons and language

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/controllers/offers_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/select2.js, app/views/offers/new.html.erb, package.json, yarn.lock
Agora o guia pode escolher sua cidade da lista do IBGE quando criar uma nova oferta.
Esta conveniência visa facilitar a futura utilização de mapas.
=> Select a city from IBGE list

Gemfile, Gemfile.lock, app/controllers/offers_controller.rb, app/controllers/pages_controller.rb, app/models/offer.rb, app/views/bookings/_form.html.erb, app/views/offers/show.html.erb, app/views/pages/search.html.erb, app/views/shared/_search.html.erb, config/routes.rb
Página de pesquisa permite localizar uma oferta pela cidade ou atividade.
Resultados são apresentados em cartões.
Página de detalhes agora apresenta formulário para agendamento (após login, se não for o próprio ofertante).
A página de pesquisa é aberta (não requer login)
Acessar funcionalidade em http://localhost:3000/search
=> Pagina de pesquisa

app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/unlocks/new.html.erb
Language changed to portuguese in some forgotten pages. Labels added. Just layout, nothing more.
=> New structures through the front

app/views/offers/index.html.erb
Front-end refatorado em offer index
=> Ux improve in offer index

app/controllers/offers_controller.rb, app/views/bookings/index.html.erb
Acrescentado sigla do estado para evitar municípios homônimos ao criar uma nova oferta
=> Adicionado sigla do estado ao campo de busca

app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
=> Layout and pieces revision and correction

.gitignore, app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/config/_colors.scss, app/views/shared/_navbar.html.erb
Cristhiano, esse é o ajuste de cores no banner.
=> ajuste de cores

app/controllers/offers_controller.rb, app/models/offer.rb, app/views/offers/new.html.erb, app/views/offers/show.html.erb
Adicionado upload de fotos e carrossel na página de agendamento da oferta.
=> Offers photos

app/assets/stylesheets/components/_banner.scss, app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/_banner.html.erb, app/views/pages/_offer_list.html.erb, app/views/pages/home.html.erb, app/views/pages/search.html.erb
Adicionadas as três últimas ofertas à página home
Refatorado o banner
=> Ofertas na home

app/controllers/bookings_controller.rb, app/controllers/offers_controller.rb, app/controllers/pages_controller.rb, app/views/bookings/show.html.erb, app/views/offers/index.html.erb
Cartão fixo para criação de novas ofertas.
Corrigido filtro de ofertas ativas na página de pesquisa.
=> Final adjusts

app/javascript/components/checkbox.js, app/javascript/packs/application.js
Agora, na página de edição de oferta, ao clicar em Desativar oferta, um prompt irá aparecer.
=> Melhorando a experiência ao ativar ou desativar oferta
